package com.sricare.microservices.dto;

import lombok.Data;

import java.util.Date;

@Data
public class BillDTO {

    private Long id;
    private String status;
    private String period;
    private Double previousDueAmount;
    private Double chargesForPeriod;
    private Date payBefore;

    // Constructors, getters, and setters are automatically generated by Lombok
}
