package com.sricare.microservices.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class BillDTO {

    private Long id;
    private String status;
    private String period;
    private Double previousDueAmount;
    private Double chargesForPeriod;
    private Date payBefore;

    // Constructors, getters, and setters are automatically generated by Lombok
}
